import os
import joblib
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, average_precision_score

# ==========================================
# 1. LOAD DATA & SPLIT CHRONOLOGICALLY
# ==========================================
# Point to the final dataset generated by the previous script
# filepath = r"C:\Users\STUDENT\OneDrive\Desktop\KTT Fellowship\ViralWatch Project\aimsktt_viralwatch\ml\dataset\final_ml_training_dataset.csv"
filepath = "/content/final_ml_training_dataset.csv"

print("1. Loading dataset...")
df = pd.read_csv(filepath)

# Ensure date is parsed correctly for the time split
df['date'] = pd.to_datetime(df['date'])

# Split the data at July 1st, 2026
# Everything before July 1st is historical training data. Everything on or after is the unseen future test data.
split_date = pd.to_datetime("2026-07-01")

train_df = df[df['date'] < split_date].copy()
test_df = df[df['date'] >= split_date].copy()

print(f"   Training rows (May/June): {len(train_df)}")
print(f"   Testing rows (July): {len(test_df)}")

# ==========================================
# 2. FEATURE ISOLATION & PREPROCESSING
# ==========================================
features = ['cumulative_confirmed_cases', 'days_since_first_case', 'pop_density', 'travel_time_to_epicenter']
target = 'target_outbreak_next_7d'

# Extract pure numbers (dropping 'date' and 'health_zone' so the models don't crash on text)
X_train = train_df[features]
y_train = train_df[target]

X_test = test_df[features]
y_test = test_df[target]

# Scale features (Crucial for Neural Networks; Random Forest doesn't mind either way)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ==========================================
# 3. BASELINE MODEL: RANDOM FOREST
# ==========================================
print("\n2. Training Scikit-Learn Random Forest Baseline...")
# class_weight='balanced' forces the tree to care about the rare outbreaks
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model.fit(X_train_scaled, y_train)

# Predictions & Probabilities
rf_preds = rf_model.predict(X_test_scaled)
rf_probs = rf_model.predict_proba(X_test_scaled)[:, 1]

print("--- Random Forest Evaluation ---")
print(classification_report(y_test, rf_preds))
print(f"PR-AUC Score: {average_precision_score(y_test, rf_probs):.4f}")

# ==========================================
# 4. DEEP LEARNING MODEL: KERAS NETWORK
# ==========================================
print("\n3. Training Keras Deep Learning Network...")

# Keep the architecture compact to prevent overfitting on 4 features
model = keras.Sequential([
    layers.Input(shape=(len(features),)),
    layers.Dense(16, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=[
        keras.metrics.Precision(name='precision'),
        keras.metrics.Recall(name='recall'),
        keras.metrics.AUC(name='pr_auc', curve='PR')
    ]
)

# Calculate dynamic class weights for Keras to handle the severe imbalance
neg, pos = np.bincount(y_train)
total = neg + pos
weight_for_0 = (1 / neg) * (total / 2.0)
weight_for_1 = (1 / pos) * (total / 2.0)
class_weights = {0: weight_for_0, 1: weight_for_1}

# Train the network
history = model.fit(
    X_train_scaled, y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_test_scaled, y_test),
    class_weight=class_weights,
    verbose=1 # Will print progress bars to the terminal
)

# Final evaluation using Keras
keras_results = model.evaluate(X_test_scaled, y_test, verbose=0)
print("\n--- Keras Network Evaluation ---")
for name, value in zip(model.metrics_names, keras_results):
    print(f"{name}: {value:.4f}")

# ==========================================
# 5. SAVE MODELS & SCALER
# ==========================================
print("\n4. Saving Models and Scaler to disk...")

# Define the models directory
# models_dir = r"C:\Users\STUDENT\OneDrive\Desktop\KTT Fellowship\ViralWatch Project\aimsktt_viralwatch\ml\models"
models_dir = "/content/models"


os.makedirs(models_dir, exist_ok=True)

# Save the Scaler
scaler_save_path = os.path.join(models_dir, "feature_scaler.joblib")
joblib.dump(scaler, scaler_save_path)
print(f"   [+] Scaler saved to: {scaler_save_path}")

# Save the Random Forest Model
rf_save_path = os.path.join(models_dir, "random_forest_baseline.joblib")
joblib.dump(rf_model, rf_save_path)
print(f"   [+] Random Forest saved to: {rf_save_path}")

# Save the Keras Model
keras_save_path = os.path.join(models_dir, "keras_outbreak_model.keras")
model.save(keras_save_path)
print(f"   [+] Keras Model saved to: {keras_save_path}")
print("\nTraining and saving pipeline complete!")